# This is a basic workflow to help you get started with Actions

name: Docker Build

on:
  push:
    branches: [ nxfilter-latest ]
  pull_request:
    branches: [ nxfilter-latest ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # optional
        password: ${{ secrets.DOCKER_PASSWORD }} # optional
